// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PBLocal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PBLocal.proto</summary>
public static partial class PBLocalReflection {

  #region Descriptor
  /// <summary>File descriptor for PBLocal.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PBLocalReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1QQkxvY2FsLnByb3RvIjUKB0FjY291bnQSCgoCaWQYASABKAkSEAoIcGFz",
          "c3dvcmQYAiABKAkSDAoEbm90ZRgDIAEoCSLKAQoIVXNlckRhdGESGwoTU2Vs",
          "ZWN0ZWRTZXJ2ZXJJbmRleBgBIAEoBRIaCghBY2NvdW50cxgCIAMoCzIILkFj",
          "Y291bnQSHAoUU2VsZWN0ZWRBY2NvdW50SW5kZXgYAyABKAUSGgoSU2NyZWVu",
          "VUlBZGFwdGF0aW9uGAQgASgCEhIKClNjZW5lU2NhbGUYBSABKAISEwoLSUFQ",
          "UmVjZWlwdHMYBiADKAkSEAoITGFuZ3VhZ2UYByABKAkSEAoIRm9udFNpemUY",
          "CCABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Account), global::Account.Parser, new[]{ "Id", "Password", "Note" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UserData), global::UserData.Parser, new[]{ "SelectedServerIndex", "Accounts", "SelectedAccountIndex", "ScreenUIAdaptation", "SceneScale", "IAPReceipts", "Language", "FontSize" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Account : pb::IMessage<Account>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Account> _parser = new pb::MessageParser<Account>(() => new Account());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Account> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PBLocalReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Account() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Account(Account other) : this() {
    id_ = other.id_;
    password_ = other.password_;
    note_ = other.note_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Account Clone() {
    return new Account(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 2;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "note" field.</summary>
  public const int NoteFieldNumber = 3;
  private string note_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Note {
    get { return note_; }
    set {
      note_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Account);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Account other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Password != other.Password) return false;
    if (Note != other.Note) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (Note.Length != 0) hash ^= Note.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (Note.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Note);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (Note.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Note);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (Note.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Note);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Account other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    if (other.Note.Length != 0) {
      Note = other.Note;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
        case 26: {
          Note = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
        case 26: {
          Note = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class UserData : pb::IMessage<UserData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PBLocalReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserData(UserData other) : this() {
    selectedServerIndex_ = other.selectedServerIndex_;
    accounts_ = other.accounts_.Clone();
    selectedAccountIndex_ = other.selectedAccountIndex_;
    screenUIAdaptation_ = other.screenUIAdaptation_;
    sceneScale_ = other.sceneScale_;
    iAPReceipts_ = other.iAPReceipts_.Clone();
    language_ = other.language_;
    fontSize_ = other.fontSize_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserData Clone() {
    return new UserData(this);
  }

  /// <summary>Field number for the "SelectedServerIndex" field.</summary>
  public const int SelectedServerIndexFieldNumber = 1;
  private int selectedServerIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SelectedServerIndex {
    get { return selectedServerIndex_; }
    set {
      selectedServerIndex_ = value;
    }
  }

  /// <summary>Field number for the "Accounts" field.</summary>
  public const int AccountsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::Account> _repeated_accounts_codec
      = pb::FieldCodec.ForMessage(18, global::Account.Parser);
  private readonly pbc::RepeatedField<global::Account> accounts_ = new pbc::RepeatedField<global::Account>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Account> Accounts {
    get { return accounts_; }
  }

  /// <summary>Field number for the "SelectedAccountIndex" field.</summary>
  public const int SelectedAccountIndexFieldNumber = 3;
  private int selectedAccountIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SelectedAccountIndex {
    get { return selectedAccountIndex_; }
    set {
      selectedAccountIndex_ = value;
    }
  }

  /// <summary>Field number for the "ScreenUIAdaptation" field.</summary>
  public const int ScreenUIAdaptationFieldNumber = 4;
  private float screenUIAdaptation_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ScreenUIAdaptation {
    get { return screenUIAdaptation_; }
    set {
      screenUIAdaptation_ = value;
    }
  }

  /// <summary>Field number for the "SceneScale" field.</summary>
  public const int SceneScaleFieldNumber = 5;
  private float sceneScale_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float SceneScale {
    get { return sceneScale_; }
    set {
      sceneScale_ = value;
    }
  }

  /// <summary>Field number for the "IAPReceipts" field.</summary>
  public const int IAPReceiptsFieldNumber = 6;
  private static readonly pb::FieldCodec<string> _repeated_iAPReceipts_codec
      = pb::FieldCodec.ForString(50);
  private readonly pbc::RepeatedField<string> iAPReceipts_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> IAPReceipts {
    get { return iAPReceipts_; }
  }

  /// <summary>Field number for the "Language" field.</summary>
  public const int LanguageFieldNumber = 7;
  private string language_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Language {
    get { return language_; }
    set {
      language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "FontSize" field.</summary>
  public const int FontSizeFieldNumber = 8;
  private int fontSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int FontSize {
    get { return fontSize_; }
    set {
      fontSize_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SelectedServerIndex != other.SelectedServerIndex) return false;
    if(!accounts_.Equals(other.accounts_)) return false;
    if (SelectedAccountIndex != other.SelectedAccountIndex) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScreenUIAdaptation, other.ScreenUIAdaptation)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SceneScale, other.SceneScale)) return false;
    if(!iAPReceipts_.Equals(other.iAPReceipts_)) return false;
    if (Language != other.Language) return false;
    if (FontSize != other.FontSize) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SelectedServerIndex != 0) hash ^= SelectedServerIndex.GetHashCode();
    hash ^= accounts_.GetHashCode();
    if (SelectedAccountIndex != 0) hash ^= SelectedAccountIndex.GetHashCode();
    if (ScreenUIAdaptation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScreenUIAdaptation);
    if (SceneScale != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SceneScale);
    hash ^= iAPReceipts_.GetHashCode();
    if (Language.Length != 0) hash ^= Language.GetHashCode();
    if (FontSize != 0) hash ^= FontSize.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SelectedServerIndex != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(SelectedServerIndex);
    }
    accounts_.WriteTo(output, _repeated_accounts_codec);
    if (SelectedAccountIndex != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(SelectedAccountIndex);
    }
    if (ScreenUIAdaptation != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(ScreenUIAdaptation);
    }
    if (SceneScale != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(SceneScale);
    }
    iAPReceipts_.WriteTo(output, _repeated_iAPReceipts_codec);
    if (Language.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Language);
    }
    if (FontSize != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(FontSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SelectedServerIndex != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(SelectedServerIndex);
    }
    accounts_.WriteTo(ref output, _repeated_accounts_codec);
    if (SelectedAccountIndex != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(SelectedAccountIndex);
    }
    if (ScreenUIAdaptation != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(ScreenUIAdaptation);
    }
    if (SceneScale != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(SceneScale);
    }
    iAPReceipts_.WriteTo(ref output, _repeated_iAPReceipts_codec);
    if (Language.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Language);
    }
    if (FontSize != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(FontSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SelectedServerIndex != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelectedServerIndex);
    }
    size += accounts_.CalculateSize(_repeated_accounts_codec);
    if (SelectedAccountIndex != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelectedAccountIndex);
    }
    if (ScreenUIAdaptation != 0F) {
      size += 1 + 4;
    }
    if (SceneScale != 0F) {
      size += 1 + 4;
    }
    size += iAPReceipts_.CalculateSize(_repeated_iAPReceipts_codec);
    if (Language.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Language);
    }
    if (FontSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FontSize);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserData other) {
    if (other == null) {
      return;
    }
    if (other.SelectedServerIndex != 0) {
      SelectedServerIndex = other.SelectedServerIndex;
    }
    accounts_.Add(other.accounts_);
    if (other.SelectedAccountIndex != 0) {
      SelectedAccountIndex = other.SelectedAccountIndex;
    }
    if (other.ScreenUIAdaptation != 0F) {
      ScreenUIAdaptation = other.ScreenUIAdaptation;
    }
    if (other.SceneScale != 0F) {
      SceneScale = other.SceneScale;
    }
    iAPReceipts_.Add(other.iAPReceipts_);
    if (other.Language.Length != 0) {
      Language = other.Language;
    }
    if (other.FontSize != 0) {
      FontSize = other.FontSize;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SelectedServerIndex = input.ReadInt32();
          break;
        }
        case 18: {
          accounts_.AddEntriesFrom(input, _repeated_accounts_codec);
          break;
        }
        case 24: {
          SelectedAccountIndex = input.ReadInt32();
          break;
        }
        case 37: {
          ScreenUIAdaptation = input.ReadFloat();
          break;
        }
        case 45: {
          SceneScale = input.ReadFloat();
          break;
        }
        case 50: {
          iAPReceipts_.AddEntriesFrom(input, _repeated_iAPReceipts_codec);
          break;
        }
        case 58: {
          Language = input.ReadString();
          break;
        }
        case 64: {
          FontSize = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SelectedServerIndex = input.ReadInt32();
          break;
        }
        case 18: {
          accounts_.AddEntriesFrom(ref input, _repeated_accounts_codec);
          break;
        }
        case 24: {
          SelectedAccountIndex = input.ReadInt32();
          break;
        }
        case 37: {
          ScreenUIAdaptation = input.ReadFloat();
          break;
        }
        case 45: {
          SceneScale = input.ReadFloat();
          break;
        }
        case 50: {
          iAPReceipts_.AddEntriesFrom(ref input, _repeated_iAPReceipts_codec);
          break;
        }
        case 58: {
          Language = input.ReadString();
          break;
        }
        case 64: {
          FontSize = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
