// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBLocal.proto

public final class PBLocal {
  private PBLocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string note = 3;</code>
     * @return The note.
     */
    java.lang.String getNote();
    /**
     * <code>string note = 3;</code>
     * @return The bytes for note.
     */
    com.google.protobuf.ByteString
        getNoteBytes();
  }
  /**
   * Protobuf type {@code Account}
   */
  public static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Account)
      AccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      id_ = "";
      password_ = "";
      note_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Account();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBLocal.internal_static_Account_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBLocal.internal_static_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBLocal.Account.class, PBLocal.Account.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object password_ = "";
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object note_ = "";
    /**
     * <code>string note = 3;</code>
     * @return The note.
     */
    @java.lang.Override
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        note_ = s;
        return s;
      }
    }
    /**
     * <code>string note = 3;</code>
     * @return The bytes for note.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(note_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, note_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(note_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, note_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBLocal.Account)) {
        return super.equals(obj);
      }
      PBLocal.Account other = (PBLocal.Account) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getNote()
          .equals(other.getNote())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + NOTE_FIELD_NUMBER;
      hash = (53 * hash) + getNote().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBLocal.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLocal.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLocal.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLocal.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLocal.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLocal.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLocal.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLocal.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLocal.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBLocal.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLocal.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLocal.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBLocal.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Account)
        PBLocal.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBLocal.internal_static_Account_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBLocal.internal_static_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBLocal.Account.class, PBLocal.Account.Builder.class);
      }

      // Construct using PBLocal.Account.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        password_ = "";
        note_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBLocal.internal_static_Account_descriptor;
      }

      @java.lang.Override
      public PBLocal.Account getDefaultInstanceForType() {
        return PBLocal.Account.getDefaultInstance();
      }

      @java.lang.Override
      public PBLocal.Account build() {
        PBLocal.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PBLocal.Account buildPartial() {
        PBLocal.Account result = new PBLocal.Account(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PBLocal.Account result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.password_ = password_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.note_ = note_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBLocal.Account) {
          return mergeFrom((PBLocal.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBLocal.Account other) {
        if (other == PBLocal.Account.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getNote().isEmpty()) {
          note_ = other.note_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                password_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                note_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        password_ = getDefaultInstance().getPassword();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object note_ = "";
      /**
       * <code>string note = 3;</code>
       * @return The note.
       */
      public java.lang.String getNote() {
        java.lang.Object ref = note_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          note_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string note = 3;</code>
       * @return The bytes for note.
       */
      public com.google.protobuf.ByteString
          getNoteBytes() {
        java.lang.Object ref = note_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          note_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string note = 3;</code>
       * @param value The note to set.
       * @return This builder for chaining.
       */
      public Builder setNote(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        note_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string note = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNote() {
        note_ = getDefaultInstance().getNote();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string note = 3;</code>
       * @param value The bytes for note to set.
       * @return This builder for chaining.
       */
      public Builder setNoteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        note_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Account)
    }

    // @@protoc_insertion_point(class_scope:Account)
    private static final PBLocal.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBLocal.Account();
    }

    public static PBLocal.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PBLocal.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 SelectedServerIndex = 1;</code>
     * @return The selectedServerIndex.
     */
    int getSelectedServerIndex();

    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    java.util.List<PBLocal.Account> 
        getAccountsList();
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    PBLocal.Account getAccounts(int index);
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    int getAccountsCount();
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    java.util.List<? extends PBLocal.AccountOrBuilder> 
        getAccountsOrBuilderList();
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    PBLocal.AccountOrBuilder getAccountsOrBuilder(
        int index);

    /**
     * <code>int32 SelectedAccountIndex = 3;</code>
     * @return The selectedAccountIndex.
     */
    int getSelectedAccountIndex();

    /**
     * <code>float ScreenUIAdaptation = 4;</code>
     * @return The screenUIAdaptation.
     */
    float getScreenUIAdaptation();

    /**
     * <code>float SceneScale = 5;</code>
     * @return The sceneScale.
     */
    float getSceneScale();

    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @return A list containing the iAPReceipts.
     */
    java.util.List<java.lang.String>
        getIAPReceiptsList();
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @return The count of iAPReceipts.
     */
    int getIAPReceiptsCount();
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @param index The index of the element to return.
     * @return The iAPReceipts at the given index.
     */
    java.lang.String getIAPReceipts(int index);
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the iAPReceipts at the given index.
     */
    com.google.protobuf.ByteString
        getIAPReceiptsBytes(int index);

    /**
     * <code>string Language = 7;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <code>string Language = 7;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();
  }
  /**
   * Protobuf type {@code UserData}
   */
  public static final class UserData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserData)
      UserDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserData.newBuilder() to construct.
    private UserData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserData() {
      accounts_ = java.util.Collections.emptyList();
      iAPReceipts_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      language_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBLocal.internal_static_UserData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBLocal.internal_static_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBLocal.UserData.class, PBLocal.UserData.Builder.class);
    }

    public static final int SELECTEDSERVERINDEX_FIELD_NUMBER = 1;
    private int selectedServerIndex_ = 0;
    /**
     * <code>int32 SelectedServerIndex = 1;</code>
     * @return The selectedServerIndex.
     */
    @java.lang.Override
    public int getSelectedServerIndex() {
      return selectedServerIndex_;
    }

    public static final int ACCOUNTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<PBLocal.Account> accounts_;
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    @java.lang.Override
    public java.util.List<PBLocal.Account> getAccountsList() {
      return accounts_;
    }
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends PBLocal.AccountOrBuilder> 
        getAccountsOrBuilderList() {
      return accounts_;
    }
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    @java.lang.Override
    public int getAccountsCount() {
      return accounts_.size();
    }
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    @java.lang.Override
    public PBLocal.Account getAccounts(int index) {
      return accounts_.get(index);
    }
    /**
     * <code>repeated .Account Accounts = 2;</code>
     */
    @java.lang.Override
    public PBLocal.AccountOrBuilder getAccountsOrBuilder(
        int index) {
      return accounts_.get(index);
    }

    public static final int SELECTEDACCOUNTINDEX_FIELD_NUMBER = 3;
    private int selectedAccountIndex_ = 0;
    /**
     * <code>int32 SelectedAccountIndex = 3;</code>
     * @return The selectedAccountIndex.
     */
    @java.lang.Override
    public int getSelectedAccountIndex() {
      return selectedAccountIndex_;
    }

    public static final int SCREENUIADAPTATION_FIELD_NUMBER = 4;
    private float screenUIAdaptation_ = 0F;
    /**
     * <code>float ScreenUIAdaptation = 4;</code>
     * @return The screenUIAdaptation.
     */
    @java.lang.Override
    public float getScreenUIAdaptation() {
      return screenUIAdaptation_;
    }

    public static final int SCENESCALE_FIELD_NUMBER = 5;
    private float sceneScale_ = 0F;
    /**
     * <code>float SceneScale = 5;</code>
     * @return The sceneScale.
     */
    @java.lang.Override
    public float getSceneScale() {
      return sceneScale_;
    }

    public static final int IAPRECEIPTS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList iAPReceipts_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @return A list containing the iAPReceipts.
     */
    public com.google.protobuf.ProtocolStringList
        getIAPReceiptsList() {
      return iAPReceipts_;
    }
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @return The count of iAPReceipts.
     */
    public int getIAPReceiptsCount() {
      return iAPReceipts_.size();
    }
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @param index The index of the element to return.
     * @return The iAPReceipts at the given index.
     */
    public java.lang.String getIAPReceipts(int index) {
      return iAPReceipts_.get(index);
    }
    /**
     * <code>repeated string IAPReceipts = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the iAPReceipts at the given index.
     */
    public com.google.protobuf.ByteString
        getIAPReceiptsBytes(int index) {
      return iAPReceipts_.getByteString(index);
    }

    public static final int LANGUAGE_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object language_ = "";
    /**
     * <code>string Language = 7;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <code>string Language = 7;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (selectedServerIndex_ != 0) {
        output.writeInt32(1, selectedServerIndex_);
      }
      for (int i = 0; i < accounts_.size(); i++) {
        output.writeMessage(2, accounts_.get(i));
      }
      if (selectedAccountIndex_ != 0) {
        output.writeInt32(3, selectedAccountIndex_);
      }
      if (java.lang.Float.floatToRawIntBits(screenUIAdaptation_) != 0) {
        output.writeFloat(4, screenUIAdaptation_);
      }
      if (java.lang.Float.floatToRawIntBits(sceneScale_) != 0) {
        output.writeFloat(5, sceneScale_);
      }
      for (int i = 0; i < iAPReceipts_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, iAPReceipts_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, language_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (selectedServerIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, selectedServerIndex_);
      }
      for (int i = 0; i < accounts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, accounts_.get(i));
      }
      if (selectedAccountIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, selectedAccountIndex_);
      }
      if (java.lang.Float.floatToRawIntBits(screenUIAdaptation_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, screenUIAdaptation_);
      }
      if (java.lang.Float.floatToRawIntBits(sceneScale_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, sceneScale_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < iAPReceipts_.size(); i++) {
          dataSize += computeStringSizeNoTag(iAPReceipts_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIAPReceiptsList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, language_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBLocal.UserData)) {
        return super.equals(obj);
      }
      PBLocal.UserData other = (PBLocal.UserData) obj;

      if (getSelectedServerIndex()
          != other.getSelectedServerIndex()) return false;
      if (!getAccountsList()
          .equals(other.getAccountsList())) return false;
      if (getSelectedAccountIndex()
          != other.getSelectedAccountIndex()) return false;
      if (java.lang.Float.floatToIntBits(getScreenUIAdaptation())
          != java.lang.Float.floatToIntBits(
              other.getScreenUIAdaptation())) return false;
      if (java.lang.Float.floatToIntBits(getSceneScale())
          != java.lang.Float.floatToIntBits(
              other.getSceneScale())) return false;
      if (!getIAPReceiptsList()
          .equals(other.getIAPReceiptsList())) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SELECTEDSERVERINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getSelectedServerIndex();
      if (getAccountsCount() > 0) {
        hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
        hash = (53 * hash) + getAccountsList().hashCode();
      }
      hash = (37 * hash) + SELECTEDACCOUNTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getSelectedAccountIndex();
      hash = (37 * hash) + SCREENUIADAPTATION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScreenUIAdaptation());
      hash = (37 * hash) + SCENESCALE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSceneScale());
      if (getIAPReceiptsCount() > 0) {
        hash = (37 * hash) + IAPRECEIPTS_FIELD_NUMBER;
        hash = (53 * hash) + getIAPReceiptsList().hashCode();
      }
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBLocal.UserData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLocal.UserData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLocal.UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLocal.UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLocal.UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLocal.UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLocal.UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLocal.UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLocal.UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBLocal.UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLocal.UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLocal.UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBLocal.UserData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserData)
        PBLocal.UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBLocal.internal_static_UserData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBLocal.internal_static_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBLocal.UserData.class, PBLocal.UserData.Builder.class);
      }

      // Construct using PBLocal.UserData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        selectedServerIndex_ = 0;
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
        } else {
          accounts_ = null;
          accountsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        selectedAccountIndex_ = 0;
        screenUIAdaptation_ = 0F;
        sceneScale_ = 0F;
        iAPReceipts_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        language_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBLocal.internal_static_UserData_descriptor;
      }

      @java.lang.Override
      public PBLocal.UserData getDefaultInstanceForType() {
        return PBLocal.UserData.getDefaultInstance();
      }

      @java.lang.Override
      public PBLocal.UserData build() {
        PBLocal.UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PBLocal.UserData buildPartial() {
        PBLocal.UserData result = new PBLocal.UserData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(PBLocal.UserData result) {
        if (accountsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            accounts_ = java.util.Collections.unmodifiableList(accounts_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.accounts_ = accounts_;
        } else {
          result.accounts_ = accountsBuilder_.build();
        }
      }

      private void buildPartial0(PBLocal.UserData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.selectedServerIndex_ = selectedServerIndex_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.selectedAccountIndex_ = selectedAccountIndex_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.screenUIAdaptation_ = screenUIAdaptation_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sceneScale_ = sceneScale_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          iAPReceipts_.makeImmutable();
          result.iAPReceipts_ = iAPReceipts_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.language_ = language_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBLocal.UserData) {
          return mergeFrom((PBLocal.UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBLocal.UserData other) {
        if (other == PBLocal.UserData.getDefaultInstance()) return this;
        if (other.getSelectedServerIndex() != 0) {
          setSelectedServerIndex(other.getSelectedServerIndex());
        }
        if (accountsBuilder_ == null) {
          if (!other.accounts_.isEmpty()) {
            if (accounts_.isEmpty()) {
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAccountsIsMutable();
              accounts_.addAll(other.accounts_);
            }
            onChanged();
          }
        } else {
          if (!other.accounts_.isEmpty()) {
            if (accountsBuilder_.isEmpty()) {
              accountsBuilder_.dispose();
              accountsBuilder_ = null;
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000002);
              accountsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAccountsFieldBuilder() : null;
            } else {
              accountsBuilder_.addAllMessages(other.accounts_);
            }
          }
        }
        if (other.getSelectedAccountIndex() != 0) {
          setSelectedAccountIndex(other.getSelectedAccountIndex());
        }
        if (other.getScreenUIAdaptation() != 0F) {
          setScreenUIAdaptation(other.getScreenUIAdaptation());
        }
        if (other.getSceneScale() != 0F) {
          setSceneScale(other.getSceneScale());
        }
        if (!other.iAPReceipts_.isEmpty()) {
          if (iAPReceipts_.isEmpty()) {
            iAPReceipts_ = other.iAPReceipts_;
            bitField0_ |= 0x00000020;
          } else {
            ensureIAPReceiptsIsMutable();
            iAPReceipts_.addAll(other.iAPReceipts_);
          }
          onChanged();
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                selectedServerIndex_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                PBLocal.Account m =
                    input.readMessage(
                        PBLocal.Account.parser(),
                        extensionRegistry);
                if (accountsBuilder_ == null) {
                  ensureAccountsIsMutable();
                  accounts_.add(m);
                } else {
                  accountsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 24: {
                selectedAccountIndex_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 37: {
                screenUIAdaptation_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 45: {
                sceneScale_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              case 50: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureIAPReceiptsIsMutable();
                iAPReceipts_.add(s);
                break;
              } // case 50
              case 58: {
                language_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int selectedServerIndex_ ;
      /**
       * <code>int32 SelectedServerIndex = 1;</code>
       * @return The selectedServerIndex.
       */
      @java.lang.Override
      public int getSelectedServerIndex() {
        return selectedServerIndex_;
      }
      /**
       * <code>int32 SelectedServerIndex = 1;</code>
       * @param value The selectedServerIndex to set.
       * @return This builder for chaining.
       */
      public Builder setSelectedServerIndex(int value) {

        selectedServerIndex_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 SelectedServerIndex = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectedServerIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        selectedServerIndex_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<PBLocal.Account> accounts_ =
        java.util.Collections.emptyList();
      private void ensureAccountsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          accounts_ = new java.util.ArrayList<PBLocal.Account>(accounts_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PBLocal.Account, PBLocal.Account.Builder, PBLocal.AccountOrBuilder> accountsBuilder_;

      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public java.util.List<PBLocal.Account> getAccountsList() {
        if (accountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accounts_);
        } else {
          return accountsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public int getAccountsCount() {
        if (accountsBuilder_ == null) {
          return accounts_.size();
        } else {
          return accountsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public PBLocal.Account getAccounts(int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);
        } else {
          return accountsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder setAccounts(
          int index, PBLocal.Account value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.set(index, value);
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder setAccounts(
          int index, PBLocal.Account.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder addAccounts(PBLocal.Account value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder addAccounts(
          int index, PBLocal.Account value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(index, value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder addAccounts(
          PBLocal.Account.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder addAccounts(
          int index, PBLocal.Account.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder addAllAccounts(
          java.lang.Iterable<? extends PBLocal.Account> values) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, accounts_);
          onChanged();
        } else {
          accountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder clearAccounts() {
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public Builder removeAccounts(int index) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.remove(index);
          onChanged();
        } else {
          accountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public PBLocal.Account.Builder getAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public PBLocal.AccountOrBuilder getAccountsOrBuilder(
          int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);  } else {
          return accountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public java.util.List<? extends PBLocal.AccountOrBuilder> 
           getAccountsOrBuilderList() {
        if (accountsBuilder_ != null) {
          return accountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accounts_);
        }
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public PBLocal.Account.Builder addAccountsBuilder() {
        return getAccountsFieldBuilder().addBuilder(
            PBLocal.Account.getDefaultInstance());
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public PBLocal.Account.Builder addAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().addBuilder(
            index, PBLocal.Account.getDefaultInstance());
      }
      /**
       * <code>repeated .Account Accounts = 2;</code>
       */
      public java.util.List<PBLocal.Account.Builder> 
           getAccountsBuilderList() {
        return getAccountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PBLocal.Account, PBLocal.Account.Builder, PBLocal.AccountOrBuilder> 
          getAccountsFieldBuilder() {
        if (accountsBuilder_ == null) {
          accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PBLocal.Account, PBLocal.Account.Builder, PBLocal.AccountOrBuilder>(
                  accounts_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          accounts_ = null;
        }
        return accountsBuilder_;
      }

      private int selectedAccountIndex_ ;
      /**
       * <code>int32 SelectedAccountIndex = 3;</code>
       * @return The selectedAccountIndex.
       */
      @java.lang.Override
      public int getSelectedAccountIndex() {
        return selectedAccountIndex_;
      }
      /**
       * <code>int32 SelectedAccountIndex = 3;</code>
       * @param value The selectedAccountIndex to set.
       * @return This builder for chaining.
       */
      public Builder setSelectedAccountIndex(int value) {

        selectedAccountIndex_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 SelectedAccountIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectedAccountIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        selectedAccountIndex_ = 0;
        onChanged();
        return this;
      }

      private float screenUIAdaptation_ ;
      /**
       * <code>float ScreenUIAdaptation = 4;</code>
       * @return The screenUIAdaptation.
       */
      @java.lang.Override
      public float getScreenUIAdaptation() {
        return screenUIAdaptation_;
      }
      /**
       * <code>float ScreenUIAdaptation = 4;</code>
       * @param value The screenUIAdaptation to set.
       * @return This builder for chaining.
       */
      public Builder setScreenUIAdaptation(float value) {

        screenUIAdaptation_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float ScreenUIAdaptation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearScreenUIAdaptation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        screenUIAdaptation_ = 0F;
        onChanged();
        return this;
      }

      private float sceneScale_ ;
      /**
       * <code>float SceneScale = 5;</code>
       * @return The sceneScale.
       */
      @java.lang.Override
      public float getSceneScale() {
        return sceneScale_;
      }
      /**
       * <code>float SceneScale = 5;</code>
       * @param value The sceneScale to set.
       * @return This builder for chaining.
       */
      public Builder setSceneScale(float value) {

        sceneScale_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>float SceneScale = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSceneScale() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sceneScale_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList iAPReceipts_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureIAPReceiptsIsMutable() {
        if (!iAPReceipts_.isModifiable()) {
          iAPReceipts_ = new com.google.protobuf.LazyStringArrayList(iAPReceipts_);
        }
        bitField0_ |= 0x00000020;
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @return A list containing the iAPReceipts.
       */
      public com.google.protobuf.ProtocolStringList
          getIAPReceiptsList() {
        iAPReceipts_.makeImmutable();
        return iAPReceipts_;
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @return The count of iAPReceipts.
       */
      public int getIAPReceiptsCount() {
        return iAPReceipts_.size();
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @param index The index of the element to return.
       * @return The iAPReceipts at the given index.
       */
      public java.lang.String getIAPReceipts(int index) {
        return iAPReceipts_.get(index);
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the iAPReceipts at the given index.
       */
      public com.google.protobuf.ByteString
          getIAPReceiptsBytes(int index) {
        return iAPReceipts_.getByteString(index);
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @param index The index to set the value at.
       * @param value The iAPReceipts to set.
       * @return This builder for chaining.
       */
      public Builder setIAPReceipts(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureIAPReceiptsIsMutable();
        iAPReceipts_.set(index, value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @param value The iAPReceipts to add.
       * @return This builder for chaining.
       */
      public Builder addIAPReceipts(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureIAPReceiptsIsMutable();
        iAPReceipts_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @param values The iAPReceipts to add.
       * @return This builder for chaining.
       */
      public Builder addAllIAPReceipts(
          java.lang.Iterable<java.lang.String> values) {
        ensureIAPReceiptsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, iAPReceipts_);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIAPReceipts() {
        iAPReceipts_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IAPReceipts = 6;</code>
       * @param value The bytes of the iAPReceipts to add.
       * @return This builder for chaining.
       */
      public Builder addIAPReceiptsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureIAPReceiptsIsMutable();
        iAPReceipts_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <code>string Language = 7;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Language = 7;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Language = 7;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string Language = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        language_ = getDefaultInstance().getLanguage();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string Language = 7;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        language_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserData)
    }

    // @@protoc_insertion_point(class_scope:UserData)
    private static final PBLocal.UserData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBLocal.UserData();
    }

    public static PBLocal.UserData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserData>
        PARSER = new com.google.protobuf.AbstractParser<UserData>() {
      @java.lang.Override
      public UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PBLocal.UserData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Account_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPBLocal.proto\"5\n\007Account\022\n\n\002id\030\001 \001(\t\022\020" +
      "\n\010password\030\002 \001(\t\022\014\n\004note\030\003 \001(\t\"\270\001\n\010UserD" +
      "ata\022\033\n\023SelectedServerIndex\030\001 \001(\005\022\032\n\010Acco" +
      "unts\030\002 \003(\0132\010.Account\022\034\n\024SelectedAccountI" +
      "ndex\030\003 \001(\005\022\032\n\022ScreenUIAdaptation\030\004 \001(\002\022\022" +
      "\n\nSceneScale\030\005 \001(\002\022\023\n\013IAPReceipts\030\006 \003(\t\022" +
      "\020\n\010Language\030\007 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Account_descriptor,
        new java.lang.String[] { "Id", "Password", "Note", });
    internal_static_UserData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserData_descriptor,
        new java.lang.String[] { "SelectedServerIndex", "Accounts", "SelectedAccountIndex", "ScreenUIAdaptation", "SceneScale", "IAPReceipts", "Language", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
